name: konta_app
description: "O Konta App: O Konta é seu assistente financeiro pessoal para uma vida financeira mais saudável e organizada. Gerencie suas finanças de forma inteligente e alcance seus objetivos financeiros com o Konta. Controle seus gastos, defina orçamentos e acompanhe suas finanças de maneira fácil e eficiente. O Konta é o aplicativo perfeito para quem deseja ter uma vida financeira mais saudável e organizada. Com o Konta, você pode controlar suas finanças de forma inteligente e alcançar seus objetivos financeiros com facilidade."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5+1
  http: ^1.6.0
  flutter_dotenv: ^5.1.0
  fl_chart: ^1.0.0
  google_mobile_ads: ^7.0.0

# Para fazer requisições HTTP (GET, POST) na API
dio: ^5.4.0

# Para gerar e formatar datas
intl: ^0.19.0

# Gerenciamento de estado e injeção de dependência simples
provider: ^6.1.1


lucide_icons: ^0.2.0

# Gráficos para o Dashboard
fl_chart: ^0.66.0

# Para armazenar o token de login de forma segura no celular
flutter_secure_storage: ^9.0.0

# Para lidar com UUIDs (identificadores únicos)
uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/logo_konta.png" # <--- CAMINHO DA LOGO
  min_sdk_android: 21 # Opcional, mas bom para compatibilidade
  # remove_alpha_ios: true # se a logo tiver transparência e der erro no iOS
